In [1]:
# NYC Citibike Program 2018 - get 2018June-August tripdata
import pandas as pd
import datetime
import numpy as np
import os

In [2]:
# Get NYC Citibike tripdata csv files from 201806 to 201808
filepath_jun = os.path.join("Resources" ,"JC-201806-citibike-tripdata.csv")
filepath_jul = os.path.join("Resources" ,"JC-201807-citibike-tripdata.csv")
filepath_aug = os.path.join("Resources" ,"JC-201808-citibike-tripdata.csv")

nycbike_2018jun = pd.read_csv(filepath_jun)
nycbike_2018jul = pd.read_csv(filepath_jul)
nycbike_2018aug = pd.read_csv(filepath_aug)

In [3]:
nycbike_2018jun.head(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,329,2018-06-01 07:07:00.2990,2018-06-01 07:12:30.2220,3183,Exchange Place,40.716247,-74.033459,3276,Marin Light Rail,40.714584,-74.042817,29513,Subscriber,1991,1
1,259,2018-06-01 08:24:43.8490,2018-06-01 08:29:03.8450,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,26221,Subscriber,1989,2
2,686,2018-06-01 09:17:49.5730,2018-06-01 09:29:16.1770,3183,Exchange Place,40.716247,-74.033459,3202,Newport PATH,40.727224,-74.033759,29266,Subscriber,1990,1
3,164,2018-06-01 09:44:00.4020,2018-06-01 09:46:44.6830,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29472,Subscriber,1993,1
4,769,2018-06-01 09:59:28.7800,2018-06-01 10:12:18.6660,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,33679,Subscriber,1977,1
5,256,2018-06-01 10:33:02.1100,2018-06-01 10:37:18.1230,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29269,Subscriber,1984,1
6,267,2018-06-01 11:33:22.6440,2018-06-01 11:37:50.0350,3183,Exchange Place,40.716247,-74.033459,3481,York St,40.716490,-74.041050,29551,Subscriber,1988,1
7,258,2018-06-01 12:07:49.8830,2018-06-01 12:12:08.0190,3183,Exchange Place,40.716247,-74.033459,3186,Grove St PATH,40.719586,-74.043117,26271,Subscriber,1976,1
8,1247,2018-06-01 12:53:24.8470,2018-06-01 13:14:11.8770,3183,Exchange Place,40.716247,-74.033459,3214,Essex Light Rail,40.712774,-74.036486,30987,Subscriber,1976,1
9,761,2018-06-01 13:21:09.2160,2018-06-01 13:33:50.9930,3183,Exchange Place,40.716247,-74.033459,3194,McGinley Square,40.725340,-74.067622,33659,Subscriber,1989,1

In [4]:
nycbike_jun_jul_aug = pd.concat([nycbike_2018jun,nycbike_2018jul,nycbike_2018aug])

In [5]:
# Output concatenated 2018 July-Aug citibike tripdata to CSV file 
filepath_2018_jun_aug = os.path.join("Resources" ,"JC-2018-jun-aug-citibike-tripdata1.csv")
nycbike_jun_jul_aug.to_csv(filepath_2018_jun_aug, index=False)
nycbike_jun_jul_aug.tail(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
44422,61445,2018-08-19 00:07:42.5450,2018-08-19 17:11:47.5880,3694,Jackson Square,40.71113,-74.0789,3694,Jackson Square,40.711130,-74.078900,26312,Customer,1969,0
44423,1331,2018-08-20 15:34:11.8060,2018-08-20 15:56:23.1780,3694,Jackson Square,40.71113,-74.0789,3677,Glenwood Ave,40.727551,-74.071061,26312,Customer,1998,2
44424,501,2018-08-20 21:55:24.4590,2018-08-20 22:03:46.1900,3694,Jackson Square,40.71113,-74.0789,3694,Jackson Square,40.711130,-74.078900,29305,Customer,1969,0
44425,1116,2018-08-22 16:10:06.0890,2018-08-22 16:28:42.8410,3694,Jackson Square,40.71113,-74.0789,3191,Union St,40.718211,-74.083639,26252,Customer,1998,2
44426,2444,2018-08-25 15:30:22.4240,2018-08-25 16:11:06.8080,3694,Jackson Square,40.71113,-74.0789,3193,Lincoln Park,40.724605,-74.078406,29493,Subscriber,1982,2
44427,462,2018-08-25 16:17:05.8840,2018-08-25 16:24:48.5890,3694,Jackson Square,40.71113,-74.0789,3194,McGinley Square,40.725340,-74.067622,29544,Subscriber,1990,1
44428,636,2018-08-28 12:31:22.4380,2018-08-28 12:41:59.2110,3694,Jackson Square,40.71113,-74.0789,3195,Sip Ave,40.730743,-74.063784,29544,Subscriber,1990,1
44429,954,2018-08-30 08:08:18.9250,2018-08-30 08:24:13.7900,3694,Jackson Square,40.71113,-74.0789,3183,Exchange Place,40.716247,-74.033459,29526,Subscriber,1977,1
44430,920,2018-08-31 08:08:54.2450,2018-08-31 08:24:14.8890,3694,Jackson Square,40.71113,-74.0789,3184,Paulus Hook,40.714145,-74.033552,33633,Subscriber,1977,1
44431,1017,2018-08-31 12:57:23.8390,2018-08-31 13:14:20.9290,3694,Jackson Square,40.71113,-74.0789,3211,Newark Ave,40.721525,-74.046305,29288,Subscriber,1964,1